const data = [
  {
    id: 1,
    img: "/mutlanee.jpg",
    file: "",
    name: "Mudhal Nee Mudivum Nee",
    author: "Fav song",
    song: "audio/muthanee.mp3",
  },
  {
    id: 2,
    img: "/yaardi.jpg",
    file: "",
    name: "Yaaradi Nee Mohini",
    author: "True Love",
    song: "audio/devathai.mp3",
  },
  {
    id: 3,
    img: "/vaamanan.jpg",
    file: "",
    name: "vaamanan",
    author: "Love",
    song: "audio/orudevathai.mp3",
  },
  {
    id: 4,
    img: "/poovinai2.jpg",
    file: "",
    name: "Ananda Thandavam",
    author: "Love",
    song: "audio/poovinai.mp3",
  },
  {
    id: 5,
    img: "/kathoramai2.jpg",
    file: "",
    name: "Neeye",
    author: "Love",
    song: "audio/kathoramai.mp3",
  },
  {
    id: 6,
    img: "/poovukellam.jpg",
    file: "",
    name: "Poovukellam",
    author: "Love",
    song: "audio/poovukellamsiragu.mp3",
  },
  {
    id: 7,
    img: "/fav.webp",
    file: "",
    name: "Manam Kothi Paravai",
    author: "nice song",
    song: "audio/favmnk.mp3",
  },
  {
    id: 8,
    img: "/fav2.jpg",
    file: "",
    name: "Manam Kothi Paravai",
    author: "Its me",
    song: "audio/mnk2.mp3",
  },

  {
    id: 9,
    img: "/nallthorum.jpg",
    file: "",
    name: "Naal thorum etho maruthu",
    author: "Love",
    song: "audio/naalthorum.mp3",
  },
  {
    id: 10,
    img: "/udalporul.jpg",
    file: "",
    name: "Udal Porul Uyire",
    author: "Love",
    song: "audio/udalporuluyire.mp3",
  },
  {
    id: 11,
    img: "/udalporul.jpg",
    file: "",
    name: "Malayin saral",
    author: "Love",
    song: "audio/malaiyinsaaralil.mp3",
  },
  {
    id: 12,
    img: "/paiya.jpg",
    file: "",
    name: "Paiya",
    author: "Love",
    song: "audio/paiyalovebgm.mp3",
  },
  {
    id: 13,
    img: "/vaaimozhintha.jpg",
    file: "",
    name: "vaaimozhintha",
    author: "Love",
    song: "audio/vaaimozhintha.mp3",
  },
  {
    id: 14,
    img: "/playlist1.png",
    file: "",
    name: "Kadhalai Solla",
    author: "Love",
    song: "audio/kadhalaisolla.mp3",
  },
  {
    id: 15,
    img: "/andrukadal.jpg",
    file: "",
    name: "Andru Kadhal Panniyathu",
    author: "Kadhal",
    song: "audio/andrukadhalpanniyathu.mp3",
  },
  {
    id: 16,
    img: "/sogathal.png",
    file: "",
    name: "Sogathal Ethuthan Maridum",
    author: "Pain",
    song: "audio/sogathalethuthanmaridum.mp3",
  },
  {
    id: 17,
    img: "/ulla.png",
    file: "",
    name: "Antha Naliley",
    author: "Fell Free",
    song: "audio/ulla.mp3",
  },
  {
    id: 18,
    img: "/sollamudiyathakadal.jpg",
    file: "",
    name: "Kadhalai Solla",
    author: "Bgm",
    song: "audio/kadhalaisollamudiyaathabgm.mp3",
  },
  {
    id: 19,
    img: "/oligalin.jpg",
    file: "",
    name: "Nallai Allai",
    author: "Bgm",
    song: "audio/oligalinthedal.mp3",
  },
  {
    id: 20,
    img: "/anbullasanthiya.jpg",
    file: "",
    name: "Anbulla Santhiya",
    author: "Failure",
    song: "audio/anubullasanthiya.mp3.mp3",
  },
  {
    id: 21,
    img: "/kazhugu.jpg",
    file: "",
    name: "Kazhugu",
    author: "Bgm",
    song: "audio/kalugu.mp3.mp3",
  },
];

export default data;
