const data = [
  {
    id: 1,
    img: "/mutlanee.jpg",
    file: "",
    name: "Mudhal Nee Mudivum Nee",
    author: "Fav song",
    song: "audio/muthanee.mp3",
  },
  {
    id: 2,
    img: "/yaardi.jpg",
    file: "",
    name: "Yaaradi Nee Mohini",
    author: "True Love",
    song: "audio/devathai.mp3",
  },
  {
    id: 3,
    img: "/vaamanan.jpg",
    file: "",
    name: "vaamanan",
    author: "Love",
    song: "audio/orudevathai.mp3",
  },
  {
    id: 4,
    img: "/poovinai.jpg",
    file: "",
    name: "Ananda Thandavam",
    author: "Love",
    song: "audio/poovinai.mp3",
  },
  {
    id: 5,
    img: "/kathoramai2.jpg",
    file: "",
    name: "Neeye",
    author: "Love",
    song: "audio/kathoramai.mp3",
  },
  {
    id: 6,
    img: "/poovukellam.jpg",
    file: "",
    name: "Poovukellam",
    author: "Love",
    song: "audio/poovukellamsiragu.mp3",
  },
  {
    id: 7,
    img: "/fav.webp",
    file: "",
    name: "Manam Kothi Paravai",
    author: "nice song",
    song: "audio/favmnk.mp3",
  },
  {
    id: 8,
    img: "/fav2.jpg",
    file: "",
    name: "Manam Kothi Paravai",
    author: "Its me",
    song: "audio/mnk2.mp3",
  },
  
  {
    id: 9,
    img: "/nallthorum.jpg",
    file: "",
    name: "Naal thorum etho maruthu",
    author: "Love",
    song: "audio/naalthorum.mp3",
  },
  // {
  //   id: 10,
  //   img: "/vijay2.jpg",
  //   file: "",
  //   name: "Geethagovindham",
  //   author: "Love",
  //   song: "audio/Inthandham.mp3",
  // },
];

export default data;
