const data = [
  {
    id: 1,
    img: "/vijay1.jpg",
    file: "",
    name: "En Roja neeye",
    author: "nice song",
    song: "audio/Inthandham.mp3",
  },
  {
    id: 2,
    img: "/ajrdy.jpg",
    file: "",
    name: "Ajun Reddy",
    author: "Its me",
    song: "audio/KurumugilSitaRamam.mp3",
  },
  {
    id: 3,
    img: "/vijay3.jpeg",
    file: "",
    name: "Kushi",
    author: "Love",
    song: "audio/SitaRamamEmotional.mp3",
  },
  {
    id: 4,
    img: "/vijay4.webp",
    file: "",
    name: "Geethagovindham",
    author: "Love",
    song: "audio/KurumugilSitaRamam.mp3",
  },
  {
    id: 5,
    img: "/vijay2.jpg",
    file: "",
    name: "Geethagovindham",
    author: "Love",
    song: "audio/Inthandham.mp3",
  },
  {
    id: 6,
    img: "/fav.webp",
    file: "",
    name: "Manam Kothi Paravai",
    author: "nice song",
    song: "audio/favmnk.mp3",
  },
  {
    id: 7,
    img: "/fav2.jpg",
    file: "",
    name: "Manam Kothi Paravai",
    author: "Its me",
    song: "audio/mnk2.mp3",
  },
  {
    id: 8,
    img: "/vijay3.jpeg",
    file: "",
    name: "Kushi",
    author: "Love",
    song: "audio/SitaRamamEmotional.mp3",
  },
  {
    id: 9,
    img: "/vijay4.webp",
    file: "",
    name: "Geethagovindham",
    author: "Love",
    song: "audio/KurumugilSitaRamam.mp3",
  },
  {
    id: 10,
    img: "/vijay2.jpg",
    file: "",
    name: "Geethagovindham",
    author: "Love",
    song: "audio/Inthandham.mp3",
  },
];

export default data;
